carchaiyo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('cars/', include('cars.urls')),
                  path('', include('home.urls')),
                  path('dashboard/', include('dashboard.urls')),
                  # path('mychat/', include('chat.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('profile/', include('myprofile.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    # car body
    path('car_body/create/', views.CarBodyCreateView.as_view(), name='car_body_create'),
    path('car_body/list/', views.CarBodyListView.as_view(), name='car_body_list'),
    path('car_body/update/<str:pk>', views.CarBodyUpdateView.as_view(), name='car_body_update'),

    # car brand
    path('car_brand/create/', views.CarBrandCreateView.as_view(), name='car_brand_create'),
    path('car_brand/list/', views.CarBrandListView.as_view(), name='car_brand_list'),
    path('car_brand/update/<str:pk>', views.CarBrandUpdateView.as_view(), name='car_brand_update'),
    #
    # car
    path('car/create', views.CarCreateView.as_view(), name='car_create'),
    path('update/<str:pk>', views.CarUpdateView.as_view(), name='car_update_view'),
    path('list/', views.CarListView.as_view(), name='car_list_view'),

]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    # # property category
    path('', views.home, name='home'),
    path('visit/req/', views.property_visit_req, name='property_visit_req'),
    path('all/users/', views.all_user, name='all_users'),
    path('my/properties/', views.my_cars, name='my_cars'),
    path('my/comments/', views.my_comment, name='my_comments'),
    path('delete/comments/', views.remove_comment, name='remove_comment'),
    path('block/user/<slug:username>', views.block_user, name='block_user'),
    path('unblock/user/<slug:username>', views.unblock_user, name='unblock_user')

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('car/desc/<str:pk>', views.car_desc, name='car_desc'),
    path('search/', views.car_search, name='car_search'),
    path('watchlist/', views.watchlist, name='car_watchlist'),
    path('request/', views.request_visit, name='request_visit'),
    path('comment/', views.comment, name='comment'),
    path('mybookmark/', views.my_bookmark, name='my_bookmark'),
    path('myvisitreq/', views.my_visit_req, name='my_visit_req'),
    path('watchlist/remove/', views.remove_watchlist, name="remove_watchlist"),
    path('contactus/', views.contactus, name="contactus"),

]

home/models.py
from django.db import models


# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    subject = models.CharField(max_length=100)
    message = models.CharField(max_length=400)

    def __str__(self):
        return self.name

home/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'message']

home/views.py
from django.contrib import messages
from django.db.models import F, Q
from django.shortcuts import render

from cars.models import Car, CarBody, CarBrand, CarWatchlist, Comments, Transmission
from django.http import Http404, HttpResponseRedirect

from .forms import ContactForm
from decorator import is_user, is_admin_or_user, is_admin


# Create your views here.
def home(request):
    car = Car.objects.filter(is_available=True).filter(is_blocked=False).filter(is_available=True)
    context = {
        'cars': car.order_by('-total_click')[:6],
        'brands': CarBrand.objects.all(),
        'bodies': CarBody.objects.all(),
        'tranmissions': Transmission.objects.all(),
        'wagon_count': car.filter(body_type__body_type='Wagon').count(),
        'pickup_count': car.filter(body_type__body_type='Pickup').count(),
        'mini_van_count': car.filter(body_type__body_type='Minivan/Van').count(),
        'crossover_count': car.filter(body_type__body_type='Crossover').count(),
        'suv_count': car.filter(body_type__body_type='SUV').count(),
        'hatchback_count': car.filter(body_type__body_type='Hatchback').count(),
        'coupe_count': car.filter(body_type__body_type='Coupe').count(),
        'sedan_count': car.filter(body_type__body_type='Sedan').count(),
    }
    # to differentiate between watchlist and non watchlist proties
    try:
        watchlist = CarWatchlist.objects.filter(user=request.user)
        watchlist_properties = []
        for watch in watchlist:
            watchlist_properties.append(watch.car)
        context['watchlist_properties'] = watchlist_properties
    except:
        pass


    return render(request, 'home/home.html', context)



def car_desc(request, pk):
    try:
        car = Car.objects.get(pk=pk)
        Car.objects.filter(pk=pk).update(total_click=F('total_click') + 1)

        comments = Comments.objects.filter(car__pk=pk).order_by('-date_of_added')
    except Car.DoesNotExist:
        raise Http404
    context = {
        'car': car,
        'comments': comments
    }

    try:
        is_requested = CarWatchlist.objects.filter(user=request.user).filter(car__pk=pk).filter(
            is_cart_visit=True).exists()
        context['is_requested'] = is_requested

    except:
        pass
    return render(request, 'home/car_desc.html', context)


# # for searching properties
def car_search(request):
    car = Car.objects.filter(is_available=True).filter(is_blocked=False).filter(is_available=True)
    context = {
        'brands': CarBrand.objects.all(),
        'bodies': CarBody.objects.all(),
        'tranmissions': Transmission.objects.all(),
    }

    if request.method == 'GET':
        if request.GET['brands']:
            brands = request.GET['brands']
        else:
            brands = 'any'

        if request.GET['bodies']:
            bodies = request.GET['bodies']
        else:
            bodies = 'bodies'

        if request.GET['tranmissions']:
            tranmissions = request.GET['tranmissions']
        else:
            tranmissions = 'any'

        # user search properties logic
        try:
            if request.GET['price']:
                price = int(request.GET['price'])
                context['price'] = price
                if price == 100000:
                    car = car.filter(price__lte=100000)
                elif price == 1000000:

                    car = car.filter(price__gt=100000).filter(price__lte=1000000)
                elif price == 5000000:
                    car = car.filter(price__gt=1000000).filter(price__lte=5000000)
                elif price == 10000000:
                    car = car.filter(price__gt=5000000).filter(price__lte=10000000)
                elif price == 10000001:
                    car = car.filter(price__gt=10000000)
                else:
                    car = car.filter(price__lt=0)

        except:
            pass
        # searching through different criteria
        if brands != 'any':
            car = car.filter(brand__brand=brands)
        if bodies != 'any':
            car = car.filter(body_type__body_type=bodies)
        if tranmissions != 'any':
            car = car.filter(transmission__transmission=tranmissions)
        if car.count() == 0:
            context['no_data'] = 'The Car is not available in this search Criteria'
        context['cars'] = car
        context['car_body'] = bodies
        context['car_brand'] = brands
        context['car_tranmissions'] = tranmissions

        try:
            watchlist = CarWatchlist.objects.filter(user=request.user)
            watchlist_properties = []
            for watch in watchlist:
                watchlist_properties.append(watch.car)
            context['watchlist_properties'] = watchlist_properties
        except:
            pass

    return render(request, 'home/car_search.html', context)

@is_admin_or_user()
def watchlist(request):
    if request.method == 'POST':
        try:
            CarWatchlist.objects.create(
                user=request.user,
                car=Car.objects.get(pk=request.POST['car_id'])
            )
        except :
            pass
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@is_admin_or_user()
def request_visit(request):
    if request.method == 'POST':
        # try:
            car_watchlist = CarWatchlist.objects.filter(user=request.user).filter(
                car__pk=request.POST['car_id'])
            if car_watchlist.exists():
                car_watchlist.update(is_cart_visit=True)
            else:
                CarWatchlist.objects.create(
                    user=request.user,
                    car=Car.objects.get(pk=request.POST['car_id']),
                    is_cart_visit=True
                )
        # except:
        #     print("error")
        #     pass

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@is_admin_or_user()
def comment(request):
    if request.method == 'POST':
        try:
            Comments.objects.create(
                user=request.user,
                car=Car.objects.get(pk=request.POST['car_id']),
                comment=request.POST['comment']
            )
            messages.success(request, 'Comment Added Successfully', extra_tags={'comment_success_message'})
        except:
            messages.success(request, 'something went wrong', extra_tags={'comment_error_message'})

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@is_admin_or_user()
def my_bookmark(request):
    context = {'bookmarks': CarWatchlist.objects.filter(user=request.user).filter(is_cart_visit=False)}
    return render(request, 'home/bookmark.html', context)


@is_admin_or_user()
def my_visit_req(request):
    context = {'bookmarks': CarWatchlist.objects.filter(user=request.user).filter(is_cart_visit=True)}
    return render(request, 'home/car_visit_req.html', context)


@is_admin_or_user()
def remove_watchlist(request):
    try:
        CarWatchlist.objects.filter(Q(car__user=request.user) | Q(user=request.user)).filter(
            car=Car.objects.get(pk=request.POST['car_id'])).delete()
    except:
        pass
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def contactus(request):
    context = {}
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            context['message'] = 'Contact form submitted successfully'
        else:
            context['message'] = form.errors
    return render(request, 'home/contactus.html', context)

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Car Chaiyo | Home</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'home/img/carousel-1.jpg' %}" rel="icon">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'home/css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/css/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'home/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom Stylesheet -->
    <link href="{% static 'home/css/style.css' %}" rel="stylesheet">
    {% block css %}
    {% endblock %}
</head>

<body>
<div class="bg-white p-0">
    <!-- Spinner Start -->
    <div id="spinner"
         class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->
    <ul class="info-top">
        <i class="fas fa-bookmark"></i> <a href="{% url 'home:my_bookmark' %}" class="text-white"><span>&nbsp; Bookmark
                    &nbsp;&nbsp;&nbsp;&nbsp;
                </span></a></li>
        <i class="fas fa-eye"></i> <a href="{% url 'home:my_visit_req' %}" class="text-white"><span>&nbsp; Visit Request&nbsp; </span></a></li>
    </ul>
    <style>
        .info-top {
            display: flex;
            justify-content: flex-end;
            align-items: center;
            /* height: 100%; */
            /* z-index: 99; */
            font-size: 12px;
            padding-right: 50px;
            line-height: 40px;
            background-color: var(--primary);
            color: var(--light);
        }
    </style>
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'comment_success_message' %}
                <div{% if message.tags == 'comment_success_message' %}
                    class="alert alert-success"
                {% else %}
                    class="alert alert-danger" {% endif %}>
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    {#<i class="fas fa-bookmark text-primary me-2"></i>#}
    <!-- Navbar Start -->
    <div class="container-fluid nav-bar bg-transparent">
        <nav class="navbar navbar-expand-lg bg-white navbar-light py-0 px-4">
            <a href="{% url 'home:home' %}" class="navbar-brand d-flex align-items-center text-center">
                <h1 class="m-0 text-primary">Car Chaiyo</h1>
            </a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ms-auto">
                    <a href="{% url 'home:home' %}" class="nav-item nav-link active">Home</a>
                    <a href="{% url 'home:car_search' %}?brands=any&bodies=any&tranmissions=any" class="nav-item nav-link">All Cars</a>
                    <a href="/contactus/" class="nav-item nav-link">Contact</a>
                </div>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'dashboard:home' %}" class="btn btn-primary px-3 mb-2 d-lg-flex">Dashboard</a>
                    {% else %}
                <a href="/accounts/login" class="btn btn-primary px-3 mb-2 d-lg-flex">LOGIN</a>

                {% endif %}
            </div>
        </nav>
    </div>
    <!-- Navbar End -->

    {% block body %}{% endblock %}

    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-white mb-4">Car Chaiyo</h5>

               <p class="mb-2">Crafting Your Drive Enjoyable And Memorable Is Our Aim. Enjoy Your Moment With
                            Our Vehicles. We Are The Best Solutions
                            For Vehicle Services.</p>

                </div>
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-white mb-4">Quick Links</h5>
                    <a class="btn btn-link text-white-50" href="{% url 'home:home' %}">Home</a>
                    <a class="btn btn-link text-white-50" href="{% url 'home:car_search' %}?brands=any&bodies=any&tranmissions=any">Property</a>
                    <a class="btn btn-link text-white-50" href="/contactus/">Contact</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-white mb-4">Get In Touch</h5>
                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>Kathmandu, Nepal</p>
                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+977-9999999999</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@carchaiyo.com</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
{#                <div class="col-lg-3 col-md-6">#}
{#                    <h5 class="text-white mb-4">Newsletter</h5>#}
{#                    <div class="position-relative mx-auto" style="max-width: 400px;">#}
{#                        <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text"#}
{#                               placeholder="Your email">#}
{#                        <button type="button"#}
{#                                class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">Subscribe#}
{#                        </button>#}
{#                    </div>#}
{#                </div>#}
            </div>
        </div>
        <div class="container">
            <div class="copyright">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        &copy; <a class="border-bottom" href="/">Car Chaiyo</a> 2022 | All Right Reserved.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
</div>

<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'home/js/wow.min.js' %}"></script>
<script src="{% static 'home/js/owl.carousel.min.js' %}"></script>

<!-- Custom Javascript -->
<script src="{% static 'home/js/main.js' %}"></script>
{% block js %}{% endblock %}
</body>

</html>

home/templates/home/car_search.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
    <!-- Search Start -->
    <form method="get" action="{% url 'home:car_search' %}">
        <div class="container-fluid bg-primary mb-5 wow fadeIn" data-wow-delay="0.1s" style="padding: 35px;">
            <div class="container">
                <div class="row g-2">
                    <div class="col-md-10">
                        <div class="row g-2">
                            <div class="col-md-4">
                                <div><h4 class="text-white">Brands</h4></div>
                                <select name="brands" class="form-select border-0 py-3">
                                    <option value="any" selected>ANY</option>

                                    {% for brand in brands %}
                                        <option value="{{ brand.brand }}">{{ brand.brand }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-md-4">
                                <div><h4 class="text-white">Bodies Type</h4></div>
                                <select name="bodies" class="form-select border-0 py-3">
                                    <option value="any" selected>Any</option>
                                    {% for body in bodies %}
                                        <option value="{{ body.body_type }}">{{ body.body_type }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-md-4">
                                <div><h4 class="text-white">Transmission
                                    </h4></div>
                                <select name="tranmissions" class="form-select border-0 py-3">
                                    <option value="any" selected>Any</option>

                                    {% for t in tranmissions %}
                                        <option value="{{ t.transmission }}">{{ t.transmission }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <button class="btn btn-dark border-0 w-100 py-3" style="margin-top: 38px;">Search</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <!-- Search End -->

    <!-- Property List Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="row g-0 gx-5 align-items-end">
                <div class="col-lg-6">
                    <div class="text-start mx-auto mb-5 wow slideInLeft" data-wow-delay="0.1s">
                        <h1 class="mb-3">Car Listing</h1>
                    </div>
                </div>
            </div>

            <div class="tab-content">

                <div id="tab-1" class="tab-pane fade show p-0 active">
                    <div class="row g-4">

                        <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                            <!-- Start Sidebar price filter section -->
                            <section id="sidebar">

                                <div class="border-bottom pb-2 ml-2">
                                    <h4 id="filter">Filter</h4>
                                </div>
                                <div class="py-2 border-bottom ml-3">
                                    <h6 class="font-weight-bold">Price Range</h6>
                                    <div id=""><span class="fa fa-minus"></span></div>
                                    <form method="get" action="{% url 'home:car_search' %}">
                                        <input type="hidden" value="{{ car_brand }}" name="brands">
                                        <input type="hidden" value="{{ car_body }}" name="bodies">
                                        <input type="hidden" value="{{ car_tranmissions }}" name="tranmissions">
                                        <div class="form-group"><input type="checkbox" value="100000" name="price"
                                                                       id="1lakh"
                                                                       {% if price == 100000 %}checked{% endif %}>
                                            <label
                                                    for="1lakh">Upto 1 Lakh</label></div>
                                        <div class="form-group"><input type="checkbox" value="1000000" name="price"
                                                                       id="10lakh"
                                                                       {% if price == 1000000 %}checked{% endif %}>
                                            <label
                                                    for="10lakh">1 Lakh - 10 Lakh</label></div>
                                        <div class="form-group"><input type="checkbox" value="5000000" name="price"
                                                                       id="50lakh"
                                                                       {% if price == 5000000 %}checked{% endif %}>
                                            <label
                                                    for="50lakh">10 Lakh - 50 Lakh</label></div>
                                        <div class="form-group"><input type="checkbox" value="10000000" name="price"
                                                                       id="1cr"
                                                                       {% if price == 10000000 %}checked{% endif %}>
                                            <label
                                                    for="1cr">50 Lakh - 1 Crore</label></div>
                                        <div class="form-group"><input type="checkbox" value="10000001" name="price"
                                                                       id="above1cr"
                                                                       {% if price == 10000001 %}checked{% endif %}>
                                            <label
                                                    for="above1cr">Above 1 Crore</label></div>
                                        <div class="form-group"><input type="submit" value="Apply Filter"
                                                                       class="btn btn-primary px-3 mb-3 mt-4"></div>

                                    </form>

                                </div>
                                <!-- End Sidebar price filter section -->
                            </section>
                        </div>
                        {% if no_data %}
                            <div class="col-lg-6 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                                <div class="alert alert-danger">{{ no_data }}</div>
                            </div>
                        {% endif %}
                        {% for car in cars %}
                            <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                                <div class="property-item rounded overflow-hidden">
                                    <div class="position-relative overflow-hidden">
                                        <a href="{% url 'home:car_desc' car.id %}"><img class="img-fluid"
                                                                                                  src="{{ car.photo.url }}"
                                                                                                  alt=""></a>
                                        <div
                                                class="bg-primary rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">
                                            {{ car.brand }}
                                        </div>
                                        <div
                                                class="bg-white rounded-top text-primary position-absolute start-0 bottom-0 mx-4 pt-1 px-3">
                                            {{ car.body_type }}
                                        </div>
                                    </div>
                                    <div class="p-4 pb-0">
                                        <h5 class="text-primary mb-3">RS. {{ car.price }}</h5>
                                        <a href="" class="d-block h5 mb-2"
                                           href="">{{ car.name }}</a>
                                        <p>
                                            <i class="fa fa-map-marker-alt text-primary me-2"></i>Km Driven: {{ car.km_driven }} K.M
                                        </p>
                                    </div>
                                    <div class="d-flex border-top">
                                        <small class="flex-fill text-center border-end py-2"><i
                                                class="fas fa-money-bill-wave text-primary me-2"></i>
                                            {% if car.is_price_negotiable %}Negotiable Price{% else %}Fixed
                                                Price{% endif %}</small>

                                        <small class="flex-fill text-center border-end py-2">
                                            <form method="post" action="{% url 'home:car_watchlist' %}">
                                                {% csrf_token %}
                                                <input type="hidden" value="{{ car.id }}" name="car_id">
                                                {% if not car in watchlist_properties %}
                                                    <button style="all: unset; cursor: pointer;"><i
                                                            class="far fa-bookmark text-primary me-2"></i> Bookmark
                                                    </button>
                                                {% else %}
                                                    <i class="fas fa-bookmark text-primary me-2"></i> Bookmarked

                                                {% endif %}

                                            </form>

                                        </small>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Property List End -->


{% endblock %}

{% block js %}
        <script
                src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script>
            $(document).ready(function () {
                $('input:checkbox').click(function () {
                    $('input:checkbox').not(this).prop('checked', false);
                });
            });
        </script>
    {% endblock %}