accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('change/password', views.password_change, name='password_change'),
    path('login/', views.login, name='login'),
    path('send/email/verification', views.send_email_verification_code, name='send_email_verification_code'),
    path('email/verify', views.verify_email, name='verify_email'),
    path('logout', views.logout, name='logout'),
    path('forget/password', views.forger_password, name='forger_password')

]

carchaiyo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('cars/', include('cars.urls')),
                  path('', include('home.urls')),
                  path('dashboard/', include('dashboard.urls')),
                  # path('mychat/', include('chat.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('profile/', include('myprofile.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    # car body
    path('car_body/create/', views.CarBodyCreateView.as_view(), name='car_body_create'),
    path('car_body/list/', views.CarBodyListView.as_view(), name='car_body_list'),
    path('car_body/update/<str:pk>', views.CarBodyUpdateView.as_view(), name='car_body_update'),

    # car brand
    path('car_brand/create/', views.CarBrandCreateView.as_view(), name='car_brand_create'),
    path('car_brand/list/', views.CarBrandListView.as_view(), name='car_brand_list'),
    path('car_brand/update/<str:pk>', views.CarBrandUpdateView.as_view(), name='car_brand_update'),
    #
    # car
    path('car/create', views.CarCreateView.as_view(), name='car_create'),
    path('update/<str:pk>', views.CarUpdateView.as_view(), name='car_update_view'),
    path('list/', views.CarListView.as_view(), name='car_list_view'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class MyUserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            username=username
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None):
        user = self.create_user(
            email,
            password=password,
            username=username
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    username = models.CharField(max_length=256, unique=True)
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    last_login = models.DateTimeField(blank=True, null=True, verbose_name="last login")
    is_email_verified = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


class EmailVerification(models.Model):
    users = models.OneToOneField(MyUser, on_delete=models.CASCADE)
    verification_code = models.CharField(max_length=6)
    created_date_time = models.DateTimeField(auto_now_add=True)
    total_try_request = models.IntegerField()
    block_time = models.DateTimeField(default='2020-01-01')

    def __str__(self):
        return self.users.email

accounts/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import MyUser
from django.contrib.auth.hashers import make_password


class MyUserCreationForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ['email', 'username', 'password']

    def clean_password(self):
        password1 = self.cleaned_data['password']
        special_sym = ['$', '@', '#', '%']
        #checking if password contains number or not
        if not any(char.isdigit() for char in password1):
            raise forms.ValidationError('Password should have at least one numeral')
        # checking if password contains uppercase or not
        if not any(char.isupper() for char in password1):
            raise forms.ValidationError('Password should have at least one uppercase letter')
        # checking if password contains is lower or not
        if not any(char.islower() for char in password1):
            raise forms.ValidationError('Password should have at least one lowercase letter')
        # checking if password contains special symbol or not
        if not any(char in special_sym for char in password1):
            raise forms.ValidationError('Password should have at least one of the symbols $@#')
        return make_password(self.cleaned_data['password'])


class ChangePasswordForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ["password"]

    def clean_password(self):
        password1 = self.cleaned_data['password']
        special_sym = ['$', '@', '#', '%']

        if not any(char.isdigit() for char in password1):
            raise forms.ValidationError('Password should have at least one numeral')

        if not any(char.isupper() for char in password1):
            raise forms.ValidationError('Password should have at least one uppercase letter')

        if not any(char.islower() for char in password1):
            raise forms.ValidationError('Password should have at least one lowercase letter')

        if not any(char in special_sym for char in password1):
            raise forms.ValidationError('Password should have at least one of the symbols $@#')
        return password1

accounts/views.py
from datetime import datetime, timezone
from random import randint
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.shortcuts import render, HttpResponse, redirect
from .models import MyUser, EmailVerification
from .forms import MyUserCreationForm, ChangePasswordForm
from django.core.mail import send_mail
from carchaiyo.settings import EMAIL_HOST_USER
from  asgiref.sync import sync_to_async
# Create your views here.


def register(request):
    if request.user.is_authenticated:
        if request.user:
            return redirect('dashboard:home')
    context = {'form': MyUserCreationForm()}
    if request.method == 'POST':
        email = request.POST.get('email')
        context['email'] = email
        if request.user.is_authenticated:
            return redirect('/')
        form = MyUserCreationForm(request.POST)
        username = request.POST.get('username')
        password1 = request.POST.get('password')
        password2 = request.POST.get('password2')
        if password1 != password2:
            context['errors'] = 'Password and conform Password didnot match'
            context['email'] = request.POST['email']
            context['username'] = username
            return render(request, 'accounts/register.html', context)
        if form.is_valid():
            form.save()
            email = email
            password = password1
            user = auth.authenticate(email=email, password=password)
            if user is not None:
                auth.login(request, user)
                return redirect('accounts:send_email_verification_code')
            else:
                context['errors'] = "something went wrong"
                return render(request, 'accounts/login.html', context)
        else:
            context['errors'] = form.errors
            context['email'] = request.POST['email']
            context['username'] = username

    return render(request, 'accounts/register.html', context)


# sending email verification code
@login_required()
def send_email_verification_code(request):
    user = request.user
    if MyUser.objects.get(email=request.user).is_email_verified:
        return HttpResponse('email already Verified')
    code = randint(100000, 999999)  # verification code
    create_date = datetime.now()
    total_try_requests = 0

    if not EmailVerification.objects.filter(users=user).exists():
        EmailVerification.objects.create(
            users=user,
            verification_code=code,
            created_date_time=create_date,
            total_try_request=total_try_requests,
        )
    else:
        email_verification = EmailVerification.objects.get(users=user)
        block_date = email_verification.block_time
        now = datetime.now(timezone.utc)
        difference = now - block_date
        if difference.total_seconds() < 300:
            return HttpResponse(f'You have been block for {difference} second')
        EmailVerification.objects.filter(users=user).update(
            verification_code=code,
            created_date_time=create_date,
            total_try_request=total_try_requests,
        )

    send_mail(
        "Email Verification Code",
        f"Your email verification code is {code}",
        EMAIL_HOST_USER,
        [EmailVerification.objects.get(users=user).users.email],
    )
    return redirect('accounts:verify_email')


@login_required()
def verify_email(request):
    if MyUser.objects.get(email=request.user).is_email_verified:
        return redirect('my_profile:profile_create')
    if request.method == 'POST':
        if MyUser.objects.get(email=request.user).is_email_verified:
            return redirect('my_profile:profile_create')

        request_code = request.POST['otp1'] + request.POST['otp2'] + request.POST['otp3'] + request.POST['otp4'] + \
                       request.POST['otp5'] + request.POST['otp6']  # code send from user to verify
        code = EmailVerification.objects.get(users=request.user).verification_code
        if request_code == code:
            MyUser.objects.filter(email=request.user).update(is_email_verified=True)
            return redirect('my_profile:profile_create')
        else:
            context = {'error': 'code you have entered is wrong'}
            return render(request, 'accounts/verify_email.html', context)
    return render(request, 'accounts/verify_email.html')


def login(request):
    if request.user.is_authenticated:
        if request.user:
            return redirect('home:home')
    if request.method == 'POST':
        if request.user.is_authenticated:
            if request.user:
                return redirect('home:home')
            else:
                return redirect('dashboard:home')
        email = request.POST['email']
        password = request.POST['password']
        user = auth.authenticate(email=email, password=password)
        if user is not None:
            auth.login(request, user)
        else:
            context = {"errors": "User name or password is incorrect", "email": request.POST['email']}
            return render(request, 'accounts/logi'
                                   'n.html', context)

        if request.user:
            return redirect('home:home')
        else:
            return redirect('home:home')
    return render(request, 'accounts/login.html')


@login_required()
def password_change(request):
    context = {}
    if request.method == 'POST':
        old_password = request.POST['old_password']
        password = request.POST['password']
        password2 = request.POST['password2']
        data = {"password": password, 'password2': password2, "old_password": old_password}
        form = ChangePasswordForm(data)
        if not request.user.check_password(old_password):
            context['errors'] = 'Your password didnot match with old password'
        elif old_password == password:
            context['errors'] = 'old password cannot be new password'
        elif password != password2:
            context['errors'] = 'your conformed password didnot matched'
        elif form.is_valid():
            MyUser.objects.filter(email=request.user).update(password=make_password(form.data['password']))
        else:
            context['errors'] = form.errors
    return render(request, 'accounts/change_password.html', context)


def logout(request):
    auth.logout(request)
    return redirect('/')


import random
import string


def forger_password(request):
    context = {}
    if request.method == 'POST':
        email = request.POST['email']
        length = 10
        lower = string.ascii_lowercase
        upper = string.ascii_uppercase
        num = string.digits
        symbols = string.punctuation
        all = lower + upper + num + symbols
        temp = random.sample(all, length)
        password = "".join(temp)
        send_mail(
            "Email Verification Code",
            f"Your email verification code is {password}",
            EMAIL_HOST_USER,
            [email],
        )
        MyUser.objects.filter(email=email).update(password=make_password(password))
        context['errors'] = 'Password has been send to your email address'
    return render(request, 'accounts/forget_password.html', context)

accounts/templates/accounts/change_password.html
{% extends 'dashboard/base.html' %}
{% block body %}
    <div class="card-body">
        <div class="container-fluid" id="container-wrapper">
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800">Change Password</h1>

            </div>

            <div class="row mb-3">
                {% if errors %}
                    <div class="container alert alert-danger">

                        {{ errors }}
                    </div>
                {% endif %}
                <!-- Earnings (Monthly) Card Example -->
                <form method="post" class="ml-4">

                    {% csrf_token %}
                    Old Password:<input type="text" class="form-control" name="old_password" required><br><br>
                    new Password:<input type="text" class="form-control" name="password" required><br><br>
                    Re-enter new Password:<input  class="form-control" type="text" name="password2" required><br><br>
                    <input type="submit" class="btn btn-info">
                </form>
                <!-- Earnings (Annual) Card Example -->

            </div>
            <!---Container Fluid-->

        </div>
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

accounts/templates/accounts/forget_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Real Estate | Login-Register</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/carousel-1.jpg' %}" rel="icon">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'home/css/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'home/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom Stylesheet -->
    <link href="{% static 'home/css/style.css' %}" rel="stylesheet">
    <!-- Login, Regsiter CSS -->
    <link rel="stylesheet" href="{% static 'login-style.css' %}">

</head>

<body>

<div class="container-xxl p-0">
    <!-- Spinner Start -->
    <div id="spinner"
         class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->


    <!-- Navbar Start -->
    <style>
        .login-nav-bar {
            position: relative;
            margin-top: 145px;
            padding: 0 3rem;
            transition: .5s;
            z-index: 9999;
        }

        .login-nav-bar.sticky-top {
            position: sticky;
            padding: 0;
            z-index: 9999;
        }

        @media (max-width: 991.98px) {
            .login-nav-bar {
                margin: 0;
                padding: 0;
            }
        }
    </style>
    <div class="container-fluid login-nav-bar bg-transparent">
        {#            <nav class="navbar navbar-expand-lg bg-white navbar-light py-0 px-4">#}
        {#                <a href="../index.html" class="navbar-brand d-flex align-items-center text-center">#}
        {##}
        {#                    <h1 class="m-0 text-primary">Real Estate</h1>#}
        {#                </a>#}
        {#                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">#}
        {#                    <span class="navbar-toggler-icon"></span>#}
        {#                </button>#}
        {#                <div class="collapse navbar-collapse" id="navbarCollapse">#}
        {#                    <div class="navbar-nav ms-auto">#}
        {#                        <a href="../index.html" class="nav-item nav-link">Home</a>#}
        {#                        <div class="nav-item dropdown">#}
        {#                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Property</a>#}
        {#                            <div class="dropdown-menu rounded-0 m-0">#}
        {#                                <a href="../property-list.html" class="dropdown-item">Property List</a>#}
        {#                                <a href="../property-desc.html" class="dropdown-item">Property Description</a>#}
        {#                            </div>#}
        {#                        </div>#}
        {##}
        {#                        <a href="../contact.html" class="nav-item nav-link">Contact</a>#}
        {#                    </div>#}
        {#                    <a href="#" class="btn btn-primary px-3 mb-2 d-lg-flex">LOGIN</a>#}
        {#                </div>#}
        {#            </nav>#}
    </div>
    <!-- Navbar End -->

    <center>
        <div class="container mt-5">
            <div class="redBg">
                <div class="box signin">
                    <h2>Already have an account?</h2>
                    <button class="signinBtn">Sign In</button>
                    <a href="/">
                        <button class="signinBtn mt-1">Back Home</button>
                    </a>

                </div>
                <div class="box signup">
                    <h2>Have an account? </h2>
                    <a class="signinBtn" href="{% url 'accounts:login' %}">
                        <button class="signupBtn mt-1">Login</button>
                    </a>
                    <a href="/">
                        <button class="signupBtn mt-1">Back Home</button>
                    </a>
                </div>
            </div>
            <div class="formBx">
                <div class="form signinform">
                    <form method="post">
                        {% csrf_token %}
                        {% if errors %}
                            <h3 class="error" style="color: red;"><b>{{ errors }}</b></h3>
                        {% endif %}
                        <h3>Forget Password</h3>
                        <input type="email" value="{{ email }}" name="email" placeholder="Enter Your Email" required>
                        <center>
                            <input type="submit" value="Reset">
                        </center>
                    </form>
                </div>

            </div>
        </div>
    </center>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'home/js/wow.min.js' %}"></script>
    <script src="{% static 'home/js/owl.carousel.min.js' %}"></script>

    <!-- Custom Javascript -->
    <script src="{% static 'home/js/main.js' %}"></script>
    <script>
        const signinBtn = document.querySelector('.signinBtn');
        const signupBtn = document.querySelector('.signupBtn');
        const formBx = document.querySelector('.formBx');
        const body = document.querySelector('body');

        signupBtn.onclick = function () {
            formBx.classList.add('active')
            body.classList.add('active')
        }
        signinBtn.onclick = function () {
            formBx.classList.remove('active')
            body.classList.remove('active')
        }
    </script>

</body>

</html>

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Real Estate | Login-Register</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/carousel-1.jpg' %}" rel="icon">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'home/css/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'home/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom Stylesheet -->
    <link href="{% static 'home/css/style.css' %}" rel="stylesheet">
    <!-- Login, Regsiter CSS -->
    <link rel="stylesheet" href="{% static 'login-style.css' %}">

</head>

<body>

<div class="container-xxl p-0">
    <!-- Spinner Start -->
    <div id="spinner"
         class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->


    <!-- Navbar Start -->
    <style>
        .login-nav-bar {
            position: relative;
            margin-top: 145px;
            padding: 0 3rem;
            transition: .5s;
            z-index: 9999;
        }

        .login-nav-bar.sticky-top {
            position: sticky;
            padding: 0;
            z-index: 9999;
        }

        @media (max-width: 991.98px) {
            .login-nav-bar {
                margin: 0;
                padding: 0;
            }
        }
    </style>
    <div class="container-fluid login-nav-bar bg-transparent">
        {#            <nav class="navbar navbar-expand-lg bg-white navbar-light py-0 px-4">#}
        {#                <a href="../index.html" class="navbar-brand d-flex align-items-center text-center">#}
        {##}
        {#                    <h1 class="m-0 text-primary">Real Estate</h1>#}
        {#                </a>#}
        {#                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">#}
        {#                    <span class="navbar-toggler-icon"></span>#}
        {#                </button>#}
        {#                <div class="collapse navbar-collapse" id="navbarCollapse">#}
        {#                    <div class="navbar-nav ms-auto">#}
        {#                        <a href="../index.html" class="nav-item nav-link">Home</a>#}
        {#                        <div class="nav-item dropdown">#}
        {#                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Property</a>#}
        {#                            <div class="dropdown-menu rounded-0 m-0">#}
        {#                                <a href="../property-list.html" class="dropdown-item">Property List</a>#}
        {#                                <a href="../property-desc.html" class="dropdown-item">Property Description</a>#}
        {#                            </div>#}
        {#                        </div>#}
        {##}
        {#                        <a href="../contact.html" class="nav-item nav-link">Contact</a>#}
        {#                    </div>#}
        {#                    <a href="#" class="btn btn-primary px-3 mb-2 d-lg-flex">LOGIN</a>#}
        {#                </div>#}
        {#            </nav>#}
    </div>
    <!-- Navbar End -->

    <center>
        <div class="container mt-5">
            <div class="redBg">
                <div class="box signin">
                    <h2>Already have an account?</h2>
                    <button class="signinBtn">Sign In</button>
                    <a href="/">
                        <button class="signinBtn mt-1">Back Home</button>
                    </a>

                </div>
                <div class="box signup">
                    <h2>Don't have an account? </h2>
                    <a class="signinBtn" href="{% url 'accounts:register' %}">
                        <button class="signupBtn mt-1">Sign Up</button>
                    </a>
                    <a href="/">
                        <button class="signupBtn mt-1">Back Home</button>
                    </a>
                </div>
            </div>
            <div class="formBx">
                <div class="form signinform">
                    <form method="post">
                        {% csrf_token %}
                        {% if errors %}
                            <h3 class="error" style="color: red;"><b>{{ errors }}</b></h3>
                        {% endif %}
                        <h3>Sign In</h3>
                        <input type="email" value="{{ email }}" name="email" placeholder="Enter Your Email" required>
                        <input type="Password" name="password" placeholder="Password" required>
                        <center>
                            <input type="submit" value="Login">
                        </center>
                    </form>
                </div>

            </div>
        </div>
    </center>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'home/js/wow.min.js' %}"></script>
    <script src="{% static 'home/js/owl.carousel.min.js' %}"></script>

    <!-- Custom Javascript -->
    <script src="{% static 'home/js/main.js' %}"></script>
    <script>
        const signinBtn = document.querySelector('.signinBtn');
        const signupBtn = document.querySelector('.signupBtn');
        const formBx = document.querySelector('.formBx');
        const body = document.querySelector('body');

        signupBtn.onclick = function () {
            formBx.classList.add('active')
            body.classList.add('active')
        }
        signinBtn.onclick = function () {
            formBx.classList.remove('active')
            body.classList.remove('active')
        }
    </script>

</body>

</html>