carchaiyo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('cars/', include('cars.urls')),
                  path('', include('home.urls')),
                  path('dashboard/', include('dashboard.urls')),
                  # path('mychat/', include('chat.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('profile/', include('myprofile.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    # car body
    path('car_body/create/', views.CarBodyCreateView.as_view(), name='car_body_create'),
    path('car_body/list/', views.CarBodyListView.as_view(), name='car_body_list'),
    path('car_body/update/<str:pk>', views.CarBodyUpdateView.as_view(), name='car_body_update'),

    # car brand
    path('car_brand/create/', views.CarBrandCreateView.as_view(), name='car_brand_create'),
    path('car_brand/list/', views.CarBrandListView.as_view(), name='car_brand_list'),
    path('car_brand/update/<str:pk>', views.CarBrandUpdateView.as_view(), name='car_brand_update'),
    #
    # car
    path('car/create', views.CarCreateView.as_view(), name='car_create'),
    path('update/<str:pk>', views.CarUpdateView.as_view(), name='car_update_view'),
    path('list/', views.CarListView.as_view(), name='car_list_view'),

]

cars/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
from accounts.models import MyUser


class CarBody(models.Model):
    body_type = models.CharField(max_length=50)

    def __str__(self):
        return self.body_type


class CarBrand(models.Model):
    brand = models.CharField(max_length=50)

    def __str__(self):
        return self.brand


class FuelType(models.Model):
    fuel = models.CharField(max_length=100)

    def __str__(self):
        return self.fuel


class Transmission(models.Model):
    transmission = models.CharField(max_length=100)

    def __str__(self):
        return self.transmission


class Car(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.PROTECT)
    name = models.CharField(max_length=200)
    photo = models.ImageField(upload_to='cars_image')
    photo2 = models.ImageField(upload_to='cars_image', null=True, blank=True)
    photo3 = models.ImageField(upload_to='cars_image', null=True, blank=True)
    photo4 = models.ImageField(upload_to='cars_image', null=True, blank=True)
    desc = RichTextField()
    brand = models.ForeignKey(CarBrand, on_delete=models.PROTECT)
    body_type = models.ForeignKey(CarBody, on_delete=models.PROTECT)
    fuel_type = models.ForeignKey(FuelType, models.PROTECT)
    transmission = models.ForeignKey(Transmission, on_delete=models.PROTECT)
    price = models.PositiveIntegerField()
    interior_color = models.CharField(max_length=100)
    engine_name = models.CharField(max_length=100)
    mileage = models.PositiveIntegerField()
    km_driven = models.PositiveIntegerField()
    added_date = models.DateTimeField(auto_now=True)
    car_number = models.CharField(max_length=30)
    total_click = models.IntegerField(default=0, blank=True, null=True)
    is_blocked = models.BooleanField(default=False)
    is_available = models.BooleanField(default=True)
    is_price_negotiable = models.BooleanField(default=False)
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class CarWatchlist(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.PROTECT)
    car = models.ForeignKey(Car, on_delete=models.PROTECT)
    is_cart_visit = models.BooleanField(default=False)

    class Meta:
        unique_together = ['user', 'car']


class Comments(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.PROTECT)
    car = models.ForeignKey(Car, on_delete=models.PROTECT)
    date_of_added = models.DateTimeField(auto_now=True)
    comment = models.CharField(max_length=1000)
    is_blocked = models.BooleanField(default=False)

    def __str__(self):
        return self.comment

cars/forms.py
from ckeditor.fields import RichTextField
from django import forms

from accounts.models import MyUser
from .models import Car, CarBody, CarBrand


class CarBodyForm(forms.ModelForm):
    class Meta:
        model = CarBody
        fields = ['body_type']
        widgets = {
            'body_type': forms.TextInput(attrs={'class': 'form-control'}),
        }


class CarBrandForm(forms.ModelForm):
    class Meta:
        model = CarBrand
        fields = ['brand']
        widgets = {
            'brand': forms.TextInput(attrs={'class': 'form-control'}),
        }


class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = [
            'user', 'photo', 'photo2', 'photo3', 'photo4', 'name', 'brand', 'body_type', 'fuel_type',
            'transmission',
            'price', 'interior_color', 'engine_name', 'desc', 'mileage', 'km_driven', 'car_number',
            'is_available', 'is_price_negotiable'
        ]
        labels = {
            'photo2': 'Photo 2 (Optional)',
            'photo3': 'Photo 3 (Optional)',
            'photo4': 'Photo 4 (Optional)',
        }
        widgets = {
            'user': forms.Select(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'brand': forms.Select(attrs={'class': 'form-control'}),
            'body_type': forms.Select(attrs={'class': 'form-control'}),
            'fuel_type': forms.Select(attrs={'class': 'form-control'}),
            'transmission': forms.Select(attrs={'class': 'form-control'}),
            'location': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),

            'interior_color': forms.TextInput(attrs={'class': 'form-control'}),
            'engine_name': forms.TextInput(attrs={'class': 'form-control'}),
            'mileage': forms.NumberInput(attrs={'class': 'form-control'}),
            'km_driven': forms.NumberInput(attrs={'class': 'form-control'}),
            'car_number': forms.TextInput(attrs={'class': 'form-control'}),

        }

    def __init__(self, user, *args, **kwargs):
        super(CarForm, self).__init__(*args, **kwargs)
        self.fields['user'].empty_label = None
        self.fields['user'].queryset = MyUser.objects.filter(email=user)

cars/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.utils.decorators import method_decorator

from .forms import CarForm, CarBodyForm, CarBrandForm
from django.views.generic import CreateView, ListView, UpdateView
from .models import CarBody, CarBrand, Transmission, FuelType, Car
from decorator import is_user, is_admin_or_user, is_admin


# Create your views here.

@method_decorator(is_admin(), name='dispatch')
class CarBodyCreateView(SuccessMessageMixin, CreateView):
    form_class = CarBodyForm
    template_name = 'cars/car_body_create_update.html'
    success_url = '/cars/car_body/list/'
    success_message = 'Car body Successfully Create'


@method_decorator(is_admin(), name='dispatch')
class CarBodyListView(ListView):
    model = CarBody
    context_object_name = 'car_body'
    template_name = 'cars/car_body_list_view.html'


@method_decorator(is_admin(), name='dispatch')
class CarBodyUpdateView(SuccessMessageMixin, UpdateView):
    form_class = CarBodyForm
    model = CarBody
    template_name = 'cars/car_body_create_update.html'
    success_url = '/cars/car_body/list/'
    success_message = 'Car body Successfully Updated'


# car brand start

@method_decorator(is_admin(), name='dispatch')
class CarBrandCreateView(SuccessMessageMixin, CreateView):
    form_class = CarBrandForm
    template_name = 'cars/car_brand_create_update.html'
    success_url = '/cars/car_brand/list/'
    success_message = 'Car Brand Successfully Create'


@method_decorator(is_admin(), name='dispatch')
class CarBrandListView(ListView):
    model = CarBrand
    context_object_name = 'car_brand'
    template_name = 'cars/car_brand_list_view.html'


@method_decorator(is_admin(), name='dispatch')
class CarBrandUpdateView(SuccessMessageMixin, UpdateView):
    form_class = CarBrandForm
    model = CarBrand
    template_name = 'cars/car_brand_create_update.html'
    success_url = '/cars/car_brand/list/'
    success_message = 'Car body Successfully Updated'


@method_decorator(is_admin_or_user(), name='dispatch')
class CarCreateView(SuccessMessageMixin, CreateView):
    form_class = CarForm
    template_name = 'cars/car_create_update.html'
    success_message = 'Car Created Successfully'
    success_url = '/dashboard/my/properties/'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


@method_decorator(is_admin(), name='dispatch')
class CarListView(ListView):
    model = Car
    context_object_name = 'cars'
    template_name = 'cars/car_list_view.html'


@method_decorator(is_admin_or_user(), name='dispatch')
class CarUpdateView(SuccessMessageMixin, UpdateView):
    form_class = CarForm
    model = Car
    template_name = 'cars/car_create_update.html'
    success_message = 'Car Created Successfully'
    success_url = '/dashboard/my/properties/'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

cars/templates/cars/car_body_create_update.html
{% extends 'dashboard/base.html' %}
{% block title %} Car Body{% endblock %}
{% block pagetitle %}Car Body Add Update{% endblock %}
{% block body %}

    <div class="card-body">


        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            {{ form.media }}
            <input type="submit" value="Create Category" class="btn btn-success">
        </form>
    </div>
{% endblock %}

cars/templates/cars/car_body_list_view.html
{% extends 'dashboard/base.html' %}
{% block title %} property{% endblock %}
{% block pagetitle %}Property{% endblock %}
{% block actionblock %}
    <a href="{% url 'cars:car_body_create' %}" class="btn btn-success">Add Car Body Type</a> {% endblock %}
{% block body %}
    <style>
        .dataTable-sorter::after, .dataTable-sorter::before {

            visibility: hidden;
        }
    </style>
    <div class="card-body">

        <table id="example" class="table table-striped table-bordered">
            <thead style="width: 100%;">
            <tr>
                <th>SN</th>
                <th>Category</th>

                <th>Action</th>

            </tr>
            </thead>
            <tbody>
            {% for body in car_body %}
                <tr>

                    <td>{{ forloop.counter }}</td>
                    <td>{{ body.body_type }}</td>
                    <td><a class="btn btn-success" href="{% url 'cars:car_body_update' body.pk %}" >Update</a></td>

                </tr>
            {% endfor %}


            </tbody>
        </table>
        <style>
            @media screen and (min-width: 250px) {
                .dataTable-input {
                    margin-top: 5px;
                    margin-right: -30px;
                }
            }
        </style>
    </div>
{% endblock %}

cars/templates/cars/car_brand.html
{% extends 'dashboard/base.html' %}
{% block title %} property{% endblock %}
{% block pagetitle %}Property{% endblock %}
{% block actionblock %}
    <a href="{% url 'cars:car_body_create' %}" class="btn btn-success">Add Car Body Type</a> {% endblock %}
{% block body %}
    <style>
        .dataTable-sorter::after, .dataTable-sorter::before {

            visibility: hidden;
        }
    </style>
    <div class="card-body">

        <table class="table table-responsive" id="table1">
            <thead style="width: 100%;">
            <tr>
                <th>SN</th>
                <th>Category</th>

                <th>Action</th>

            </tr>
            </thead>
            <tbody>
            {% for body in car_body %}
                <tr>

                    <td>{{ forloop.counter }}</td>
                    <td>{{ body.body_type }}</td>
                    <td><a class="btn btn-success" href="{% url 'cars:car_body_update' body.pk %}" >Update</a></td>

                </tr>
            {% endfor %}


            </tbody>
        </table>
        <style>
            @media screen and (min-width: 250px) {
                .dataTable-input {
                    margin-top: 5px;
                    margin-right: -30px;
                }
            }
        </style>
    </div>
{% endblock %}

cars/templates/cars/car_brand_create_update.html
{% extends 'dashboard/base.html' %}
{% block title %} Car Brand{% endblock %}
{% block pagetitle %}Car Brand Add Update{% endblock %}
{% block body %}

    <div class="card-body">

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            {{ form.media }}
            <input type="submit" value="Create Category" class="btn btn-success">
        </form>
    </div>
{% endblock %}

cars/templates/cars/car_brand_list_view.html
{% extends 'dashboard/base.html' %}
{% block title %} Car Brand{% endblock %}
{% block pagetitle %}Car Brand{% endblock %}
{% block actionblock %}
    <a href="{% url 'cars:car_brand_create' %}" class="btn btn-success">Add Car Brand</a> {% endblock %}
{% block body %}
    <style>
        .dataTable-sorter::after, .dataTable-sorter::before {
            visibility: hidden;
        }
    </style>
    <div class="card-body">
        <table id="example" class="table table-striped table-bordered">
            <thead style="width: 100%;">
            <tr>
                <th>SN</th>
                <th>Category</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% for brand in car_brand %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ brand.brand }}</td>
                    <td><a class="btn btn-success" href="{% url 'cars:car_brand_update' brand.pk %}">Update</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <style>
            @media screen and (min-width: 250px) {
                .dataTable-input {
                    margin-top: 5px;
                    margin-right: -30px;
                }
            }
        </style>
    </div>
{% endblock %}

cars/templates/cars/car_create_update.html
{% extends 'dashboard/base.html' %}
{% block title %} Car{% endblock %}
{% block pagetitle %}Car Create{% endblock %}
{% block actionblock %}
 {% endblock %}
{% block body %}

    <div class="card-body">

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            {{ form.media }}
            <input type="submit" value="Create Category" class="btn btn-success">
        </form>
    </div>
{% endblock %}

cars/templates/cars/car_list_view.html
{% extends 'dashboard/base.html' %}
{% block title %} Cars{% endblock %}
{% block pagetitle %}Cars{% endblock %}
{% block actionblock %}<a href="{% url 'cars:car_create' %}" class="btn btn-success">Add Cars</a> {% endblock %}
{% block body %}
    <style>
        .dataTable-sorter::after, .dataTable-sorter::before {

            visibility: hidden;
        }
    </style>
    <div class="card-body">

        <table id="example" class="table table-striped table-bordered">
            <thead style="width: 100%;">
            <tr>
                <th>SN</th>
                <th>user</th>
                <th>name</th>
                <th>photo</th>
                <th>brand</th>
                <th>body_type</th>
                <th>fuel_type</th>
                <th>transmission</th>
                <th>Desc</th>
                <th>Added Date</th>
                <th>price</th>
                <th>interior_color</th>
                <th>engine_name</th>
                <th>mileage</th>
                <th>is_available</th>
                <th>is_price_negotiable</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% for car in cars %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ car.user }}</td>
                    <td>{{ car.name }}</td>
                    <td><img src="{{ car.photo.url }}" height="50" width="65"></td>
                    <td>{{ car.brand }}</td>
                    <td>{{ car.body_type }}</td>
                    <td>{{ car.fuel_type }}</td>
                    <td>{{ car.transmission }}</td>
                    <td>{{ car.desc|safe|slice:25 }}</td>
                    <td>{{ car.added_date|date:"Y-m-d" }}</td>
                    <td>{{ car.price }}</td>
                    <td>{{ car.interior_color }}</td>
                    <td>{{ car.engine_name }}</td>
                    <td>{{ car.mileage }}</td>
                    <td>{{ car.is_available }}</td>
                    <td>{{ car.is_price_negotiable }}</td>
                    <td><a href="{% url 'cars:car_update_view' car.pk %}" class="btn btn-danger">Update</a> </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <style>
            @media screen and (min-width: 250px) {
                .dataTable-input {
                    margin-top: 5px;
                    margin-right: -30px;
                }
            }
        </style>
    </div>
{% endblock %}