accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('change/password', views.password_change, name='password_change'),
    path('login/', views.login, name='login'),
    path('send/email/verification', views.send_email_verification_code, name='send_email_verification_code'),
    path('email/verify', views.verify_email, name='verify_email'),
    path('logout', views.logout, name='logout'),
    path('forget/password', views.forger_password, name='forger_password')

]

carchaiyo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('cars/', include('cars.urls')),
                  path('', include('home.urls')),
                  path('dashboard/', include('dashboard.urls')),
                  # path('mychat/', include('chat.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('profile/', include('myprofile.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    # car body
    path('car_body/create/', views.CarBodyCreateView.as_view(), name='car_body_create'),
    path('car_body/list/', views.CarBodyListView.as_view(), name='car_body_list'),
    path('car_body/update/<str:pk>', views.CarBodyUpdateView.as_view(), name='car_body_update'),

    # car brand
    path('car_brand/create/', views.CarBrandCreateView.as_view(), name='car_brand_create'),
    path('car_brand/list/', views.CarBrandListView.as_view(), name='car_brand_list'),
    path('car_brand/update/<str:pk>', views.CarBrandUpdateView.as_view(), name='car_brand_update'),
    #
    # car
    path('car/create', views.CarCreateView.as_view(), name='car_create'),
    path('update/<str:pk>', views.CarUpdateView.as_view(), name='car_update_view'),
    path('list/', views.CarListView.as_view(), name='car_list_view'),

]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    # # property category
    path('', views.home, name='home'),
    path('visit/req/', views.property_visit_req, name='property_visit_req'),
    path('all/users/', views.all_user, name='all_users'),
    path('my/properties/', views.my_cars, name='my_cars'),
    path('my/comments/', views.my_comment, name='my_comments'),
    path('delete/comments/', views.remove_comment, name='remove_comment'),
    path('block/user/<slug:username>', views.block_user, name='block_user'),
    path('unblock/user/<slug:username>', views.unblock_user, name='unblock_user')

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('car/desc/<str:pk>', views.car_desc, name='car_desc'),
    path('search/', views.car_search, name='car_search'),
    path('watchlist/', views.watchlist, name='car_watchlist'),
    path('request/', views.request_visit, name='request_visit'),
    path('comment/', views.comment, name='comment'),
    path('mybookmark/', views.my_bookmark, name='my_bookmark'),
    path('myvisitreq/', views.my_visit_req, name='my_visit_req'),
    path('watchlist/remove/', views.remove_watchlist, name="remove_watchlist"),
    path('contactus/', views.contactus, name="contactus"),

]

myprofile/urls.py
from django.urls import path
from . import views

app_name = 'my_profile'

urlpatterns = [

    path('create/', views.CreateProfile.as_view(), name='profile_create'),
    path('view/', views.ProfileListView.as_view(), name='profile_list_view'),
    path('update/', views.ProfileUpdateView.as_view(), name='profile_update'),

]

dashboard/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models


# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    subject = models.CharField(max_length=100)
    message = models.CharField(max_length=400)

    def __str__(self):
        return self.name

home/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'message']

dashboard/views.py
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render
# Create your views here.
from accounts.models import MyUser
from decorator import is_user, is_admin_or_user, is_admin
from cars.models import CarWatchlist, Comments, Car, CarBody,CarBrand


@is_admin_or_user()
def home(request):
    context = {
        'total_cars': Car.objects.all().count(),
        'total_comments': Comments.objects.all().count(),
        'total_car_body_type': CarBody.objects.all().count(),
        'total_users': MyUser.objects.all().count(),
        'total_book_marked': CarWatchlist.objects.all().count(),
        'total_car_brand': CarBrand.objects.all().count()
    }
    return render(request, 'dashboard/home.html', context)


@is_admin_or_user()
def property_visit_req(request):
    car_visit_list = CarWatchlist.objects.filter(car__user=request.user)
    context = {"car_visit_list": car_visit_list}
    return render(request, 'dashboard/car_visit_request.html', context)


@is_admin()
def all_user(request):
    context = {
        'users': MyUser.objects.all()

    }
    return render(request, 'dashboard/users_list.html', context)


@is_admin_or_user()
def my_cars(request):
    context = {
        'cars': Car.objects.filter(user=request.user)
    }
    return render(request, 'cars/car_list_view.html', context)


@is_admin_or_user()
def my_comment(request):
    context = {
        'comments': Comments.objects.filter(Q(car__user=request.user) | Q(user=request.user)).order_by(
            '-date_of_added')
    }
    return render(request, 'dashboard/my_comments.html', context)


@is_admin_or_user()
def remove_comment(request):
    if request.method == 'POST':
        try:
            Comments.objects.filter(Q(car__user=request.user) | Q(user=request.user)).filter(pk=request.POST['pk']).delete()
        except:
            pass

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@is_admin_or_user()
def block_user(request, username):
    try:
        MyUser.objects.filter(username=username).update(is_active=False)
    except:
        pass
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@is_admin_or_user()
def unblock_user(request, username):
    try:
        MyUser.objects.filter(username=username).update(is_active=True)
    except:
        pass
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

home/views.py
from django.contrib import messages
from django.db.models import F, Q
from django.shortcuts import render

from cars.models import Car, CarBody, CarBrand, CarWatchlist, Comments, Transmission
from django.http import Http404, HttpResponseRedirect

from .forms import ContactForm
from decorator import is_user, is_admin_or_user, is_admin


# Create your views here.
def home(request):
    car = Car.objects.filter(is_available=True).filter(is_blocked=False).filter(is_available=True)
    context = {
        'cars': car.order_by('-total_click')[:6],
        'brands': CarBrand.objects.all(),
        'bodies': CarBody.objects.all(),
        'tranmissions': Transmission.objects.all(),
        'wagon_count': car.filter(body_type__body_type='Wagon').count(),
        'pickup_count': car.filter(body_type__body_type='Pickup').count(),
        'mini_van_count': car.filter(body_type__body_type='Minivan/Van').count(),
        'crossover_count': car.filter(body_type__body_type='Crossover').count(),
        'suv_count': car.filter(body_type__body_type='SUV').count(),
        'hatchback_count': car.filter(body_type__body_type='Hatchback').count(),
        'coupe_count': car.filter(body_type__body_type='Coupe').count(),
        'sedan_count': car.filter(body_type__body_type='Sedan').count(),
    }
    # to differentiate between watchlist and non watchlist proties
    try:
        watchlist = CarWatchlist.objects.filter(user=request.user)
        watchlist_properties = []
        for watch in watchlist:
            watchlist_properties.append(watch.car)
        context['watchlist_properties'] = watchlist_properties
    except:
        pass


    return render(request, 'home/home.html', context)



def car_desc(request, pk):
    try:
        car = Car.objects.get(pk=pk)
        Car.objects.filter(pk=pk).update(total_click=F('total_click') + 1)

        comments = Comments.objects.filter(car__pk=pk).order_by('-date_of_added')
    except Car.DoesNotExist:
        raise Http404
    context = {
        'car': car,
        'comments': comments
    }

    try:
        is_requested = CarWatchlist.objects.filter(user=request.user).filter(car__pk=pk).filter(
            is_cart_visit=True).exists()
        context['is_requested'] = is_requested

    except:
        pass
    return render(request, 'home/car_desc.html', context)


# # for searching properties
def car_search(request):
    car = Car.objects.filter(is_available=True).filter(is_blocked=False).filter(is_available=True)
    context = {
        'brands': CarBrand.objects.all(),
        'bodies': CarBody.objects.all(),
        'tranmissions': Transmission.objects.all(),
    }

    if request.method == 'GET':
        if request.GET['brands']:
            brands = request.GET['brands']
        else:
            brands = 'any'

        if request.GET['bodies']:
            bodies = request.GET['bodies']
        else:
            bodies = 'bodies'

        if request.GET['tranmissions']:
            tranmissions = request.GET['tranmissions']
        else:
            tranmissions = 'any'

        # user search properties logic
        try:
            if request.GET['price']:
                price = int(request.GET['price'])
                context['price'] = price
                if price == 100000:
                    car = car.filter(price__lte=100000)
                elif price == 1000000:

                    car = car.filter(price__gt=100000).filter(price__lte=1000000)
                elif price == 5000000:
                    car = car.filter(price__gt=1000000).filter(price__lte=5000000)
                elif price == 10000000:
                    car = car.filter(price__gt=5000000).filter(price__lte=10000000)
                elif price == 10000001:
                    car = car.filter(price__gt=10000000)
                else:
                    car = car.filter(price__lt=0)

        except:
            pass
        # searching through different criteria
        if brands != 'any':
            car = car.filter(brand__brand=brands)
        if bodies != 'any':
            car = car.filter(body_type__body_type=bodies)
        if tranmissions != 'any':
            car = car.filter(transmission__transmission=tranmissions)
        if car.count() == 0:
            context['no_data'] = 'The Car is not available in this search Criteria'
        context['cars'] = car
        context['car_body'] = bodies
        context['car_brand'] = brands
        context['car_tranmissions'] = tranmissions

        try:
            watchlist = CarWatchlist.objects.filter(user=request.user)
            watchlist_properties = []
            for watch in watchlist:
                watchlist_properties.append(watch.car)
            context['watchlist_properties'] = watchlist_properties
        except:
            pass

    return render(request, 'home/car_search.html', context)

@is_admin_or_user()
def watchlist(request):
    if request.method == 'POST':
        try:
            CarWatchlist.objects.create(
                user=request.user,
                car=Car.objects.get(pk=request.POST['car_id'])
            )
        except :
            pass
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@is_admin_or_user()
def request_visit(request):
    if request.method == 'POST':
        # try:
            car_watchlist = CarWatchlist.objects.filter(user=request.user).filter(
                car__pk=request.POST['car_id'])
            if car_watchlist.exists():
                car_watchlist.update(is_cart_visit=True)
            else:
                CarWatchlist.objects.create(
                    user=request.user,
                    car=Car.objects.get(pk=request.POST['car_id']),
                    is_cart_visit=True
                )
        # except:
        #     print("error")
        #     pass

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@is_admin_or_user()
def comment(request):
    if request.method == 'POST':
        try:
            Comments.objects.create(
                user=request.user,
                car=Car.objects.get(pk=request.POST['car_id']),
                comment=request.POST['comment']
            )
            messages.success(request, 'Comment Added Successfully', extra_tags={'comment_success_message'})
        except:
            messages.success(request, 'something went wrong', extra_tags={'comment_error_message'})

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@is_admin_or_user()
def my_bookmark(request):
    context = {'bookmarks': CarWatchlist.objects.filter(user=request.user).filter(is_cart_visit=False)}
    return render(request, 'home/bookmark.html', context)


@is_admin_or_user()
def my_visit_req(request):
    context = {'bookmarks': CarWatchlist.objects.filter(user=request.user).filter(is_cart_visit=True)}
    return render(request, 'home/car_visit_req.html', context)


@is_admin_or_user()
def remove_watchlist(request):
    try:
        CarWatchlist.objects.filter(Q(car__user=request.user) | Q(user=request.user)).filter(
            car=Car.objects.get(pk=request.POST['car_id'])).delete()
    except:
        pass
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def contactus(request):
    context = {}
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            context['message'] = 'Contact form submitted successfully'
        else:
            context['message'] = form.errors
    return render(request, 'home/contactus.html', context)

dashboard/templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Datatables - Car Rental</title>

    <!-- Main Styles -->
    <link rel="stylesheet" href="{% static 'dashboard/assets/styles/style.css' %}">

    <!-- Material Design Icon -->
    <link rel="stylesheet" href="{% static 'dashboard/assets/fonts/material-design/css/materialdesignicons.css' %}">

    <!-- Data Tables -->
    <link rel="stylesheet" href="{% static 'dashboard/assets/plugin/datatables/dataTables.bootstrap.min.css' %}">

</head>

<body>
<div class="main-menu">
    <header class="header">
        <a href="/" class="logo"><i class="ico mdi mdi-cube-outline"></i>Car Chaiyo</a>
        <button type="button" class="button-close fa fa-times js__menu_close"></button>
        <div class="user">
            <a href="#" class="avatar"><img src="{% static 'dashboard/assets/images/avatar.jpg' %}" alt=""><span
                    class="status online"></span></a>
            <h5 class="name"><a href="{% url 'my_profile:profile_list_view' %}">{{ request.user }}</a></h5>
            <!-- /.name -->

            <!-- /.control-wrap -->
        </div>
        <!-- /.user -->
    </header>
    <!-- /.header -->
    <div class="content">

        <div class="navigation">
            <h5 class="title">Home</h5>
            <!-- /.title -->
            <ul class="menu js__accordion">
                <li>
                    <a class="waves-effect" href="{% url 'dashboard:home' %}"><i
                            class="menu-icon mdi mdi-view-dashboard"></i><span>Dashboard</span></a>
                </li>
            </ul>
            <!-- /.menu js__accordion -->
            <h5 class="title">Pages</h5>
            {% if request.user.is_authenticated %}
                <ul class="menu js__accordion">
                    <li>
                        <a class="waves-effect" href="{% url 'my_profile:profile_list_view' %}"><i
                                class="menu-icon mdi mdi-view-dashboard"></i><span>My Profile</span></a>
                    </li>
                </ul>
                <ul class="menu js__accordion">
                    <li>
                        <a class="waves-effect" href="{% url 'dashboard:my_cars' %}"><i
                                class="menu-icon mdi mdi-view-dashboard"></i><span>My Car List </span></a>
                    </li>
                </ul>
                <ul class="menu js__accordion">
                    <li>
                        <a class="waves-effect" href="{% url 'accounts:password_change' %}"><i
                                class="menu-icon mdi mdi-view-dashboard"></i><span>Change Password </span></a>
                    </li>
                </ul>
                <ul class="menu js__accordion">
                    <li>
                        <a class="waves-effect" href="{% url 'dashboard:my_comments' %}"><i
                                class="menu-icon mdi mdi-view-dashboard"></i><span>Comment List </span></a>
                    </li>
                </ul>
                <ul class="menu js__accordion">
                    <li>
                        <a class="waves-effect" href="{% url 'dashboard:property_visit_req' %}"><i
                                class="menu-icon mdi mdi-view-dashboard"></i><span>Car Visit Request </span></a>
                    </li>
                </ul>


            {% endif %}

            {% if request.user.is_admin %}
                <!-- /.title -->

                <ul class="menu js__accordion">
                    <li>
                        <a class="waves-effect" href="{% url 'dashboard:all_users' %}"><i
                                class="menu-icon mdi mdi-view-dashboard"></i><span>All Users</span></a>
                    </li>
                </ul>
                <ul class="menu js__accordion">
                    <li>
                        <a class="waves-effect" href="{% url 'cars:car_body_list' %}"><i
                                class="menu-icon mdi mdi-view-dashboard"></i><span>Car Body List </span></a>
                    </li>
                </ul>
                <ul class="menu js__accordion">
                    <li>
                        <a class="waves-effect" href="{% url 'cars:car_brand_list' %}"><i
                                class="menu-icon mdi mdi-view-dashboard"></i><span>Car Brand List </span></a>
                    </li>
                </ul>

                <ul class="menu js__accordion">
                    <li>
                        <a class="waves-effect" href="{% url 'cars:car_list_view' %}"><i
                                class="menu-icon mdi mdi-view-dashboard"></i><span>Car List </span></a>
                    </li>
                </ul>
            {% endif %}
        <ul class="menu js__accordion">
                    <li>
                        <a class="waves-effect" href="{% url 'accounts:logout' %}"><i
                                class="menu-icon mdi mdi-view-dashboard"></i><span>Logout </span></a>
                    </li>
                </ul>
            <!-- /.menu js__accordion -->

        </div>
        <!-- /.navigation -->
    </div>
    <!-- /.content -->
</div>
<!-- /.main-menu -->

<div class="fixed-navbar">
    <div class="pull-left">
        <button type="button"
                class="menu-mobile-button glyphicon glyphicon-menu-hamburger js__menu_mobile"></button>
        <h1 class="page-title">{% block title %}{% endblock %}</h1>
        <!-- /.page-title -->
    </div>
    <!-- /.pull-left -->
<div class="pull-right">
			<div class="ico-item">
                {% block actionblock %}{% endblock %}

				<!-- /.searchform -->
			</div>
			<!-- /.ico-item -->

		</div>
    <!-- /.pull-right -->
</div>
<!-- /.fixed-navbar -->

<div id="wrapper">
    <div class="main-content">
        <div class="row small-spacing">
            <div class="col-xs-12">
                <div class="box-content">
                    <!-- /.dropdown js__dropdown -->
                    <div class="table-responsive">

                        {% block body %}{% endblock %}

                    </div>
                </div>
                <!-- /.box-content -->
            </div>
            <!-- /.col-xs-12 -->
        </div>
    </div>
    <!-- /.main-content -->
</div>
<!--/#wrapper -->

<script src="{% static 'dashboard/assets/scripts/jquery.min.js' %}"></script>
<script src="{% static 'dashboard/assets/plugin/nprogress/nprogress.js' %}"></script>

<!-- Data Tables -->
<script src="{% static 'dashboard/assets/plugin/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'dashboard/assets/plugin/datatables/dataTables.bootstrap.min.js' %}"></script>
<script src="{% static 'dashboard/assets/plugin/datatables/datatables.demo.min.js' %}"></script>
<script src="{% static 'dashboard/assets/scripts/main.js' %}"></script>

</body>

</html>

dashboard/templates/dashboard/car_visit_request.html
{% extends 'dashboard/base.html' %}
{% block title %} Car Visit Request{% endblock %}
{% block pagetitle %}Car Visit Request{% endblock %}
{% block body %}
    <style>
        .dataTable-sorter::after, .dataTable-sorter::before {

            visibility: hidden;
        }
    </style>
    <div class="card-body">

        <table id="example" class="table table-striped table-bordered">
            <thead style="width: 100%;">
            <tr>
                <tr>
                        <th>Car</th>
                        <th>Users</th>
                        <th>Price</th>
                        <th>Brand</th>
                        <th>IS price Negotiable</th>
                        <th>IS Car Available</th>
                        <th>Remove</th>
                    </tr>

            </tr>
            </thead>
            <tbody>
            {% for bookmark in car_visit_list %}
                <tr>
                            <td class="align-middle"><img src="{{ bookmark.car.photo.url }}" alt="" style="width: 50px;">
                                {{ bookmark.property.name }}
                            </td>
                            <td class="align-middle">{{ bookmark.car.user }}</td>
                            <td class="align-middle">Rs. {{ bookmark.car.price }}</td>
                            <td class="align-middle">{{ bookmark.car.brand }}</td>
                            <td class="align-middle">{{ bookmark.car.is_price_negotiable }}</td>
                            <td class="align-middle">{{ bookmark.car.is_available }}</td>
                            <td class="align-middle">
                                <form method="post" action="{% url 'home:remove_watchlist' %}">
                                    {% csrf_token %}
                                    <input type="hidden" value="{{ bookmark.car.pk }}" name="car_id">
                                    <button class="btn btn-sm btn-primary">Remove</button>
                                </form>
                            </td>
                        </tr>
            {% endfor %}

            </tbody>
        </table>
        <style>
            @media screen and (min-width: 250px) {
                .dataTable-input {
                    margin-top: 5px;
                    margin-right: -30px;
                }
            }
        </style>
    </div>
{% endblock %}

dashboard/templates/dashboard/home.html
{% extends 'dashboard/base.html' %}
{% block title %}Dashboard {% endblock %}
{% block pagetitle %}Dashboard {% endblock %}

{% block dashboard_active %}active{% endblock %}
{% block body %}

    <div class="page-content">
                <section class="row">
                    <div class="col-12 col-lg-12">
                        <div class="row">
                            <div class="col-6 col-lg-4 col-md-6">
                                <div class="card">
                                    <div class="card-body px-3 py-4-5">
                                        <div class="row">
                                            <div class="col-md-4">
                                                <div class="stats-icon purple">
                                                    <i class="bi-people-fill"></i>
                                                </div>
                                            </div>
                                            <div class="col-md-8">
                                                <h6 class="text-muted font-semibold">Total Users</h6>
                                                <h6 class="font-extrabold mb-0">{{ total_users }}</h6>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6 col-lg-4 col-md-6">
                                <div class="card">
                                    <div class="card-body px-3 py-4-5">
                                        <div class="row">
                                            <div class="col-md-4">
                                                <div class="stats-icon blue">
                                                    <i class="bi bi-building"></i>
                                                </div>
                                            </div>
                                            <div class="col-md-8">
                                                <h6 class="text-muted font-semibold">Total Cars</h6>
                                                <h6 class="font-extrabold mb-0">{{ total_cars }}</h6>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6 col-lg-4 col-md-6">
                                <div class="card">
                                    <div class="card-body px-3 py-4-5">
                                        <div class="row">
                                            <div class="col-md-4">
                                                <div class="stats-icon green">
                                                    <i class="bi bi-chat"></i>
                                                </div>
                                            </div>
                                            <div class="col-md-8">
                                                <h6 class="text-muted font-semibold">Total Comment</h6>
                                                <h6 class="font-extrabold mb-0">{{ total_comments }}</h6>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6 col-lg-4 col-md-6">
                                <div class="card">
                                    <div class="card-body px-3 py-4-5">
                                        <div class="row">
                                            <div class="col-md-4">
                                                <div class="stats-icon red">
                                                    <i class="bi bi-bookmark-dash-fill"></i>
                                                </div>
                                            </div>
                                            <div class="col-md-8">
                                                <h6 class="text-muted font-semibold">Total Car Bookmarked</h6>
                                                <h6 class="font-extrabold mb-0">{{ total_book_marked }}</h6>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </section>
            </div>
{% endblock %}

dashboard/templates/dashboard/my_comments.html
{% extends 'dashboard/base.html' %}
{% block title %} Comment{% endblock %}
{% block pagetitle %}Comment{% endblock %}
{% block body %}
    <style>
        .dataTable-sorter::after, .dataTable-sorter::before {

            visibility: hidden;
        }
    </style>
    <div class="card-body">

        <table id="example" class="table table-striped table-bordered">
            <thead style="width: 100%;">
            <tr>
                <th>SN</th>
                <th>Commented By</th>
                <th>Car Owner</th>
                <th>Date</th>
                <th>Date</th>
                <th>Action</th>
                <th>Action</th>

            </tr>
            </thead>
            <tbody>
            {% for comment in comments %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ comment.user.username }}</td>
                    <td>{{ comment.car.user.username }}</td>
                    <td>{{ comment.comment }}</td>
                    <td>{{ comment.date_of_added|date:'y-m-d' }}</td>
                    <td><a href="{% url 'home:car_desc' comment.car.pk %}" class="btn btn-success">Car Desc</a> </td>
                    <td><form method="post" action="{% url 'dashboard:remove_comment' %}">
                        {% csrf_token %}
                        <input type="hidden" name="pk" value="{{ comment.pk }}">
                        <input type="Submit" value="Remove Comment" href="{% url 'dashboard:remove_comment' %}" class="btn btn-success">
                    </form></td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
        <style>
            @media screen and (min-width: 250px) {
                .dataTable-input {
                    margin-top: 5px;
                    margin-right: -30px;
                }
            }
        </style>
    </div>
{% endblock %}